[package]
name = "rdkafka"
version = "0.6.0"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]
repository = "https://github.com/fede1024/rust-rdkafka"
readme = "README.md"
license = "MIT"
description = "Rust wrapper for librdkafka"
keywords = ["kafka", "rdkafka"]

[dependencies]
rdkafka-sys = { path = "rdkafka-sys", version = "0.9.2-4" }
clap = "2.18.0"
env_logger = "^0.3.0"
errno = "^0.1.8"
futures = "^0.1.7"
libc = "^0.2.0"
log = "^0.3.0"

[features]
default = []

ssl = ["rdkafka-sys/ssl"]
sasl = ["rdkafka-sys/sasl", "ssl"]
